[build]
builder = "NIXPACKS"
buildCommand = "./mvnw clean package -DskipTests"

[deploy]
startCommand = "java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/*.jar"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
